name: Sync-GitHub-to-Gitee
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        # 必选，需要同步的Github用户（源）
        src: github/whereof
        # 必选，需要同步到的Gitee的用户（目的）
        dst: gitee/whereof
        # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
        dst_token: ${{ secrets.GITEE_TOKEN }}
        # 直接取当前项目的仓库名
        static_list: ${{ github.event.repository.name }}

